import axios from "axios";
import type { IReciter, IReciterProvider, IAyahAudioSource, ProviderHealth } from "./types";

export class EveryAyahProvider implements IReciterProvider {
	name = "EveryAyah CDN (Verse-by-Verse)";
	type = "every-ayah" as const;
	private cdnBaseUrl = "https://everyayah.com/data";

	private curatedReciters: (IReciter & { cdnFolder: string })[] = [
		{
			id: "ea-dossari",
			nameArabic: "ياسر الدوسري",
			nameEnglish: "Yasser Al-Dossari",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "تلاوة حزينة خاشعة",
			provider: "every-ayah",
			cdnFolder: "Yasser_Ad-Dussary_128kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 1,
			previewAudio: "https://everyayah.com/data/Yasser_Ad-Dussary_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-minshawi-murattal",
			nameArabic: "محمد صديق المنشاوي",
			nameEnglish: "Mohamed Siddiq Al-Minshawi",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Minshawy_Murattal_128kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 2,
			previewAudio: "https://everyayah.com/data/Minshawy_Murattal_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-minshawi-mujawwad",
			nameArabic: "محمد صديق المنشاوي",
			nameEnglish: "Mohamed Siddiq Al-Minshawi (Mujawwad)",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مجود خاشع",
			provider: "every-ayah",
			cdnFolder: "Minshawy_Mujawwad_192kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 3,
			previewAudio: "https://everyayah.com/data/Minshawy_Mujawwad_192kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-muaiqly",
			nameArabic: "ماهر المعيقلي",
			nameEnglish: "Maher Al-Muaiqly",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Maher_AlMuaiqly_64kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 4,
			previewAudio: "https://everyayah.com/data/Maher_AlMuaiqly_64kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-ghamdi",
			nameArabic: "سعد الغامدي",
			nameEnglish: "Saad Al-Ghamdi",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Ghamadi_40kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 5,
			previewAudio: "https://everyayah.com/data/Ghamadi_40kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-qatami",
			nameArabic: "ناصر القطامي",
			nameEnglish: "Nasser Al-Qatami",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "تلاوة خاشعة",
			provider: "every-ayah",
			cdnFolder: "Nasser_Alqatami_128kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 6,
			previewAudio: "https://everyayah.com/data/Nasser_Alqatami_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-shatri",
			nameArabic: "أبو بكر الشاطري",
			nameEnglish: "Abu Bakr Al-Shatri",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Abu_Bakr_Ash-Shaatree_128kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 7,
			previewAudio: "https://everyayah.com/data/Abu_Bakr_Ash-Shaatree_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-husary-mujawwad",
			nameArabic: "محمود خليل الحصري",
			nameEnglish: "Mahmoud Khalil Al-Husary (Mujawwad)",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مجود",
			provider: "every-ayah",
			cdnFolder: "Husary_128kbps_Mujawwad",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 8,
			previewAudio: "https://everyayah.com/data/Husary_128kbps_Mujawwad/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-ajamy",
			nameArabic: "أحمد بن علي العجمي",
			nameEnglish: "Ahmed Al-Ajamy",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل خاشع",
			provider: "every-ayah",
			cdnFolder: "ahmed_ibn_ali_al_ajamy_128kbps",
			availability: "FULL",
			enabled: true,
			featured: true,
			priority: 9,
			previewAudio: "https://everyayah.com/data/ahmed_ibn_ali_al_ajamy_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-bukhatir",
			nameArabic: "صلاح بوخاطر",
			nameEnglish: "Salah Bukhatir",
			countryCode: "KW",
			countryArabic: "الإمارات",
			countryEnglish: "UAE",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Salaah_AbdulRahman_Bukhatir_128kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 10,
			previewAudio: "https://everyayah.com/data/Salaah_AbdulRahman_Bukhatir_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-rifai",
			nameArabic: "هاني الرفاعي",
			nameEnglish: "Hani Ar-Rifai",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "تلاوة بايكية",
			provider: "every-ayah",
			cdnFolder: "Hani_Rifai_192kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 11,
			previewAudio: "https://everyayah.com/data/Hani_Rifai_192kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-ayyoub",
			nameArabic: "محمد أيوب",
			nameEnglish: "Muhammad Ayyub",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل حجازي",
			provider: "every-ayah",
			cdnFolder: "Muhammad_Ayyoub_128kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 12,
			previewAudio: "https://everyayah.com/data/Muhammad_Ayyoub_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-jaber",
			nameArabic: "علي جابر",
			nameEnglish: "Ali Jaber",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل الحرم المكي",
			provider: "every-ayah",
			cdnFolder: "Ali_Jaber_64kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 13,
			previewAudio: "https://everyayah.com/data/Ali_Jaber_64kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-tablawi",
			nameArabic: "محمد محمود الطبلاوي",
			nameEnglish: "Mohammad Al-Tablawi",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مجود",
			provider: "every-ayah",
			cdnFolder: "Mohammad_al_Tablaway_128kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 14,
			previewAudio: "https://everyayah.com/data/Mohammad_al_Tablaway_128kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-ismail",
			nameArabic: "مصطفى إسماعيل",
			nameEnglish: "Mustafa Ismail",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مجود",
			provider: "every-ayah",
			cdnFolder: "Mustafa_Ismail_48kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 15,
			previewAudio: "https://everyayah.com/data/Mustafa_Ismail_48kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-banna",
			nameArabic: "محمود علي البنا",
			nameEnglish: "Mahmoud Ali Al-Banna",
			countryCode: "EG",
			countryArabic: "مصر",
			countryEnglish: "Egypt",
			qiraat: "حفص عن عاصم",
			style: "مجود",
			provider: "every-ayah",
			cdnFolder: "mahmoud_ali_al_banna_32kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 16,
			previewAudio: "https://everyayah.com/data/mahmoud_ali_al_banna_32kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-abbad",
			nameArabic: "فارس عباد",
			nameEnglish: "Fares Abbad",
			countryCode: "KW",
			countryArabic: "اليمن",
			countryEnglish: "Yemen",
			qiraat: "حفص عن عاصم",
			style: "تلاوة شجية",
			provider: "every-ayah",
			cdnFolder: "Fares_Abbad_64kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 17,
			previewAudio: "https://everyayah.com/data/Fares_Abbad_64kbps/001001.mp3",
			availableSurahsCount: 114,
		},
		{
			id: "ea-juhany",
			nameArabic: "عبد الله عواد الجهني",
			nameEnglish: "Abdullah Al-Juhany",
			countryCode: "SA",
			countryArabic: "السعودية",
			countryEnglish: "Saudi Arabia",
			qiraat: "حفص عن عاصم",
			style: "مرتل",
			provider: "every-ayah",
			cdnFolder: "Abdullaah_3awwaad_Al-Juhaynee_128kbps",
			availability: "FULL",
			enabled: true,
			featured: false,
			priority: 18,
			previewAudio: "https://everyayah.com/data/Abdullaah_3awwaad_Al-Juhaynee_128kbps/001001.mp3",
			availableSurahsCount: 114,
		}
	];

	async getReciters(): Promise<IReciter[]> {
		return this.curatedReciters;
	}

	async getAyahAudio(
		reciterId: string,
		surah: number,
		ayah: number
	): Promise<IAyahAudioSource> {
		const reciter = this.curatedReciters.find((r) => r.id === reciterId);
		if (!reciter) {
			throw new Error(`Reciter ${reciterId} not found in EveryAyah provider`);
		}

		const surahFormatted = surah.toString().padStart(3, "0");
		const ayahFormatted = ayah.toString().padStart(3, "0");
		const fileName = `${surahFormatted}${ayahFormatted}.mp3`;
		const url = `${this.cdnBaseUrl}/${reciter.cdnFolder}/${fileName}`;

		return {
			url,
			reciterId,
			surah,
			ayah,
		};
	}

	async getPreviewAudio(reciterId: string): Promise<string> {
		const reciter = this.curatedReciters.find((r) => r.id === reciterId);
		return reciter?.previewAudio || "https://everyayah.com/data/Yasser_Ad-Dussary_128kbps/001001.mp3";
	}

	async isAvailable(reciterId: string): Promise<boolean> {
		const reciter = this.curatedReciters.find((r) => r.id === reciterId);
		return !!reciter && reciter.enabled;
	}

	async checkHealth(): Promise<ProviderHealth> {
		try {
			await axios.get(`${this.cdnBaseUrl}/Yasser_Ad-Dussary_128kbps/001001.mp3`, {
				headers: { Range: "bytes=0-50" },
				timeout: 4000,
			});
			return "ONLINE";
		} catch {
			return "DEGRADED";
		}
	}
}
